name: Scrape Executive Orders

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch latest data and upload
        run: python scrape.py

      - name: Commit and push changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if [[ $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Automated commit: Updates detected"
            git push
          fi
